name: Deploy Docker Compose configuration workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docker Compose configuration job
    runs-on: ubuntu-24.04

    steps:
      - name: Deploy Docker Compose configuration step
        uses: Danand/deploy-docker-compose@v0.1.0
        with:
          ssh-private-key: '${{ secrets.SSH_PRIVATE_KEY }}'
          ssh-host: '${{ secrets.SSH_HOST }}'
          ssh-user: 'root'
          docker-compose-env-file-path: '.env'
          docker-compose-env-file-content: |
            INA_SPEECH_SEGMENTER_BOT_TOKEN="${{ secrets.INA_SPEECH_SEGMENTER_BOT_TOKEN }}"
